python main.py --device 2 \
               --seed 0 \
               --save_root ../outs/tmp \
               --data_root ../data \
               --optimizer AdamW \
               --epochs 10 \
               --bs 32 \
               --lr 1e-5 \
               --warmup_steps 1000 \
               --steps_saving 1 \
               -v